name: Build Check

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build:
    name: "Build Check"
    runs-on: docker
    container:
      image: archlinux:latest
    steps:
      - name: Install deps
        run: pacman --noconfirm -Sy make git mtools xorriso dosfstools cdrtools wget nodejs
        
      - name: Install Zig
        run: wget https://kage.sj.strangled.net/zigup-bin.pkg.tar.zst && pacman --noconfirm -U zigup-bin.pkg.tar.zst && zigup 0.13.0
        
      - uses: https://code.forgejo.org/forgejo/upload-artifact@v4
      - name: Build
        run: make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: AeroOS.iso
        